### ISSUE TITLE
Can't rn on mac Mojave 10.14.5

### ISSUE THREAD

**Issue by maheshkurmi** [cout970/Modeler#10]
jar file terminates with following message
```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'
terminating with uncaught exception of type NSException
abort() called
```

In console follwing error is shown

```
java.lang.RuntimeException: Failed to create a GLFW window
	at com.cout970.glutilities.window.WindowBuilder.create(WindowBuilder.kt:34)
	at com.cout970.modeler.input.window.WindowHandler.create(WindowHandler.kt:131)
	at com.cout970.modeler.Initializer.init(Initializer.kt:105)
	at com.cout970.modeler.MainKt.main(Main.kt:21)
[2021-4-14][0:54:49] Eng of log
```

**Comment by cout970** [comment]
Try running the program with -XstartOnFirstThread, ie.
`java -XstartOnFirstThread -jar modeler-2.3-beta.jar`

I don't have a mac so I cannot test it

**Comment by maheshkurmi** [comment]
Still does't run ! On console I get following error
...........
..........
[2021-4-15][11:16:16] Starting GLFW window
java.lang.RuntimeException: Failed to create a GLFW window
	at com.cout970.glutilities.window.WindowBuilder.create(WindowBuilder.kt:34)
	at com.cout970.modeler.input.window.WindowHandler.create(WindowHandler.kt:131)
	at com.cout970.modeler.Initializer.init(Initializer.kt:105)
	at com.cout970.modeler.MainKt.main(Main.kt:21)
[2021-4-15][11:16:16] Eng of log
